#!/bin/bash

DEB_BUILD_GNU_TYPE=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)

echo "/usr/lib/distcc/$DEB_BUILD_GNU_TYPE-gcc" '$@' > /usr/local/bin/invoke-distcc-gcc
chmod a+x /usr/local/bin/invoke-distcc-gcc
echo "/usr/lib/distcc/$DEB_BUILD_GNU_TYPE-g++" '$@' > /usr/local/bin/invoke-distcc-g++
chmod a+x /usr/local/bin/invoke-distcc-g++
