#!/bin/bash

DEB_BUILD_GNU_TYPE=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)

GCC_VERSION=
#GCC_VERSION=-4.4

echo "/usr/lib/distcc/$DEB_BUILD_GNU_TYPE-gcc$GCC_VERSION" '$@' > /usr/local/bin/invoke-distcc-gcc
chmod a+x /usr/local/bin/invoke-distcc-gcc

echo "/usr/lib/distcc/$DEB_BUILD_GNU_TYPE-g++$GCC_VERSION" '$@' > /usr/local/bin/invoke-distcc-g++
chmod a+x /usr/local/bin/invoke-distcc-g++
